### PR TITLE
Update recipe to version 1.20

### PR DESCRIPTION
**Pull request by rmax**

### CODE REVIEW

**Comment by rmax** [comment]
Friendly nudge.

**Comment by jakirkham** [comment]
Hey @rmax. Thanks for the version bump. Seems like a good idea to get this in. Though have not looked into whether this might break ABI. Do you happen to know? If not, I can try to look into it next week.

**Comment by rmax** [comment]
I haven't look deeply if this release mantains ABI compatibility.

**Comment by rmax** [comment]
How can we test ABI compatibility?

**Comment by jakirkham** [comment]
Sorry to drop the ball on this, @rmax. Let's get this in.

These days we just check [ABI Laboratory]( https://abi-laboratory.pro/ ). Based on the [API/ABI Report]( https://abi-laboratory.pro/tracker/timeline/leveldb/ ) for LevelDB, this looks good. We may need to use different pinnings going forward, but I don't think it is of any major concern.

**Comment by jakirkham** [comment]
@conda-forge-admin, please update circle.

**Pull request merged**
